name: CLDR Modify

env:
  CLDR_DIR: ${{ github.workspace }}
  CLDR_JAR: ${{ github.workspace }}/tools/cldr-code/target/cldr-code.jar

on:
  push:
    branches:
      - 'srl295/cldr-16083/continuous-cldr-modify'
  # workflow_dispatch:
  #   inputs:
  #     cldr-ref:
  #       description: CLDR ref to build
  #       required: true
  #       default: 'main'
  #     cldr-repo:
  #       description: CLDR repo to build
  #       required: true
  #       default: 'unicode-org/cldr'
jobs:
  modify:
    name: Run CLDRModify
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone CLDR
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.event.inputs.cldr-ref }}
          lfs: false
          # repository: ${{ github.event.inputs.cldr-repo }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('tools/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      ## The point of this was to try to separate out the deps from
      ## the build. But, it seems to add time even if deps are already fetched.
      # - name: Maven deps
      #   run: >
      #     mvn -s .github/workflows/mvn-settings.xml -B dependency:resolve --file=tools/pom.xml -pl cldr-code
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        # compile only, we don't want to take the time to package
        run: >
          mvn -s .github/workflows/mvn-settings.xml -B compile --file tools/pom.xml
          -DskipTests=true -pl cldr-code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run CLDR-modify common/main
        run: >
          export TMPD=$(mktemp -d)
          CLDR_DIR=$(pwd) ;
          LANG=en_US.UTF-8
          mvn -s .github/workflows/mvn-settings.xml -B
          "-DCLDR_DIR=${CLDR_DIR}"
          --file=tools/pom.xml
          -pl cldr-code
          -Dfile.encoding=utf-8 exec:java
          -Dexec.mainClass=org.unicode.cldr.tool.CLDRModify
          -Dexec.args="modify -d${TMPD} -s$(pwd)/common/main" &&
          mv -v ${TMPD}/*.xml common/main/
      - name: Check on Changes
        run: |
          echo '### Changes' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          git status | tee -a $GITHUB_STEP_SUMMARY
          git diff --stat | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Update branch
        run: |
          git config user.name 'Steven R. Loomis [bot]'
          git config user.email 'srloomis@unicode.org'
          git add common/main
          git commit -am $(git log --pretty=%s HEAD | head -1 | cut -d' ' -f1)' CLDRModify from '$(git log --pretty=%h -n 1 HEAD)
          git checkout -b auto/test
          # reset origin using token
          git remote set-url origin "https://srl295:${GH_TOKEN}@github.com/srl295/cldr.git"
          git push --set-upstream -f origin auto/test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Open PR
        run: |
          gh pr create \
            --title $(git log --pretty=%s HEAD | head -1 | cut -d' ' -f1)" auto: CLDRModify" \
            --body $(git log --pretty=%s HEAD | head -1 | cut -d' ' -f1)" Automatically created, etc" \
            --base 'srl295/cldr-16083/continuous-cldr-modify' \
            --head $(git rev-parse --abbrev-ref HEAD) \
        env:
          GH_TOKEN: ${{ github.token }}

